name: Terraform Plan and Apply

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1" # every Monday at 00:00 UTC
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  plan:
    runs-on: ubuntu-22.04
    permissions: { id-token: write, contents: read }
    container:
      image: ockawin/v1-app-infra-ci:edge-amd64
      options: --pid host --ipc host
    defaults:
      run: { shell: sh }
    steps:
      - name: Checkout repository
        run: |
          chown root:root .
          git init
          git remote add origin "https://oauth:${{ github.token }}@github.com/${{ github.repository }}.git"
          git fetch origin --depth=1 ${{ github.ref }}
          git reset --hard FETCH_HEAD
      - name: Terraform Init
        run: terraform init
      - name: Terraform plan
        run: terraform plan -out=tfplan
      - name: Prepare AWS
        run: |
          mkdir ~/.aws
          echo "[default]" >> ~/.aws/config
          echo "region = us-east-1" >> ~/.aws/config
          echo "s3 =" >> ~/.aws/config
          echo "    signature_version = s3v4" >> ~/.aws/config
          echo "[default]" >> ~/.aws/credentials
          echo "aws_access_key_id=${{ secrets.ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${{ secrets.SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
      - name: Upload tfplan to S3
        run: |
          alias aws='aws --endpoint-url ${{ secrets.ENDPOINT_URL }}'
          aws s3 cp tfplan s3://${{ secrets.BUCKET }}/${{ github.repository }}/${{ github.sha }}.tfplan

# @todo check for drift, exit if not
